### ISSUE TITLE
无法连接至EA服务器

### ISSUE THREAD

**Issue by Pavel-Ivanovich-Batov** [CrazyZhang666/EAappEmulater#10]
We're sorry, an error has occurred
We are unable to connect to EA servers to activate Battlefield 1 on this computer using your account. Please try again later.
软件日志一切正常，但是启动后EA错误弹窗如此显示
![edd25175791e268ebe14bcd28c332128](https://github.com/user-attachments/assets/6831f62e-684a-4f58-bd06-955ddf98963f)

**Comment by 761123300** [comment]
请检查你的网络

**Comment by Pavel-Ivanovich-Batov** [comment]
> 请检查你的网络
开关加速器、换加速器、换网络环境、关防火墙已经全试过了……

**Comment by CrazyZhang666** [comment]
重启下电脑，重置下网络
