### ISSUE TITLE
希望能添加命令行启动功能

### ISSUE THREAD

**Issue by coxychen** [CrazyZhang666/EAappEmulater#14]
能够支持通过命令行参数/快捷方式调用EAappEmulater直接启动某个游戏，这样不需要点击多次

**Comment by 761123300** [comment]
关于这个如果你是需要战地1或者更老的战地直接启动的话可以试试战地1吧去年发布的免origin补丁

**Comment by coxychen** [comment]
> 关于这个如果你是需要战地1或者更老的战地直接启动的话可以试试战地1吧去年发布的免origin补丁

EAFC好像没有这种补丁呢

**Comment by 761123300** [comment]
> > 关于这个如果你是需要战地1或者更老的战地直接启动的话可以试试战地1吧去年发布的免origin补丁
> 
> EAFC好像没有这种补丁呢

FIFA的话那就只能等未来更新这个功能了
