### ISSUE TITLE
试玩版好像有些问题

### ISSUE THREAD

**Issue by scx1125** [CrazyZhang666/EAappEmulater#23]
试玩版好像有些问题，许可证会获取不到

**Comment by 761123300** [comment]
试玩版游戏一般来说不支持，毕竟和正式版许可证以及主程序不一样

**Comment by scx1125** [comment]
> 试玩版游戏一般来说不支持，毕竟和正式版许可证以及主程序不一样

也就是说如果我换了主程序和试玩版许可证就可以了吗

**Comment by 761123300** [comment]
> > 试玩版游戏一般来说不支持，毕竟和正式版许可证以及主程序不一样
> 
> 也就是说如果我换了主程序和试玩版许可证就可以了吗

唯一的解决办法是买完整版游戏
