### ISSUE TITLE
模拟器里怎么添加游戏

### ISSUE THREAD

**Issue by 575658** [CrazyZhang666/EAappEmulater#24]
游戏库里没有fa25，希望作者添加进去

**Comment by 761123300** [comment]
fc25？这游戏目前ea会员只能试玩10小时，我无法使用试玩许可证添加支持

**Comment by 575658** [comment]
我给你提供个正规号，你添加下许可，方便加个V&nbsp; &nbsp; &nbsp;china1370000




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/EAappEmulater"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月23日(星期一) 下午4:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/EAappEmulater] 模拟器里怎么添加游戏 (Issue #24)






fc25？这游戏目前ea会员只能试玩10小时，我无法使用试玩许可证添加支持

**Comment by 575658** [comment]
现在fc25就开服了，等着用这个紫EA，实在是太爱了，比烂橘子登录强多了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/EAappEmulater"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月23日(星期一) 晚上6:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/EAappEmulater] 模拟器里怎么添加游戏 (Issue #24)






这个问题不大，等到时候战地1eaac更新的时候我会顺便添加上这玩意

**Comment by 575658** [comment]
辛苦作者尽快更新FC   烂EA 太不好用了

**Comment by 575658** [comment]
作者大大，能都麻烦您更新下fc25.辛苦了，如果方便加个好友，有事情请教😊





------------------ 原始邮件 ------------------
发件人: Misaka_Mikoto_01 ***@***.***&gt;
发送时间: 2024年9月23日 16:39
收件人: CrazyZhang666/EAappEmulater ***@***.***&gt;
抄送: 575658 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [CrazyZhang666/EAappEmulater] 模拟器里怎么添加游戏 (Issue #24)





 
fc25？这游戏目前ea会员只能试玩10小时，我无法使用试玩许可证添加支持

**Comment by 761123300** [comment]
> 作者大大，能都麻烦您更新下fc25.辛苦了，如果方便加个好友，有事情请教😊
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Misaka_Mikoto_01 ***@***.***&gt; 发送时间: 2024年9月23日 16:39 收件人: CrazyZhang666/EAappEmulater ***@***.***&gt; 抄送: 575658 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [CrazyZhang666/EAappEmulater] 模拟器里怎么添加游戏 (Issue #24) fc25？这游戏目前ea会员只能试玩10小时，我无法使用试玩许可证添加支持 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


等战地1反作弊更新后就一起加上，然后有什么问题可以直接在这里说

**Comment by 575658** [comment]
> > 作者大大，能都麻烦您更新下fc25.辛苦了，如果方便加个好友，有事情请教 😊 [...](#) ------------------ 原始邮件 ------------------ 发件人： Misaka_Mikoto_01 _**@**_._**> 发送时间： 2024年9月23日 16：39 收件人： CrazyZhang666/EAappEmulater _**@**_.**_> 抄送： 575658 _**@**_._**>，作者 _**@**_。**_> 主题： Re： [CrazyZhang666/EAappEmulater] 模拟器里怎么添加游戏 （Issue #24） fc25？这游戏目前ea会员只能试玩10小时，我无法使用试玩许可证添加支持 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您编写了该线程。消息 ID：_**@**_.***>
> 
> 等战地1反作弊更新后就一起加上，然后有什么问题可以直接在这里说

我这有个项目，想请老师合作看看，如果有兴趣的话
