### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by Xuan-BOMS** [CrazyZhang666/EAappEmulater#30]
在模拟器中可正常用steam登录获取cookie，但无法在模拟器里登录
![屏幕截图 2024-10-02 023848](https://github.com/user-attachments/assets/dc0a6bd0-ec75-4f56-ba3b-78840e9d329d)
![屏幕截图 2024-10-02 023826](https://github.com/user-attachments/assets/6f3ea127-ca0f-4513-a877-83baa41410ca)

**Comment by 761123300** [comment]
请将程序改名为EADesktop.exe然后再挂加速器启动试试
