### ISSUE TITLE
关于FC25试玩号登录

### ISSUE THREAD

**Issue by huanghuixin1** [CrazyZhang666/EAappEmulater#40]
我试了一下修改启动参数
```csharp
environmentVariables["EAFreeTrialGame"] = "true";
environmentVariables["ContentId"] = "198387_oa";
```
但是在`EAAntiCheat.GameServiceLauncher.exe`启动以后，还是会打开`FC25.exe`而不是应有的`FC25_trial.exe`

是否可以指导一下，或者有偿请二位开发大佬支持一下这个功能

可以的话麻烦加我一下Q  3096664196  或者麻烦开发大佬留一个联系方式
感谢

（非常冒昧，但是实在找不到联系方式）

**Comment by 761123300** [comment]
抽时间看看

**Comment by scx1125** [comment]
> 不需要了谢谢

请问是怎么解决的
