### ISSUE TITLE
获取本账号头像失败

### ISSUE THREAD

**Issue by SomunsMo** [CrazyZhang666/EAappEmulater#5]
Bug截图：
![Snipaste_2024-07-25_11-39-32](https://github.com/user-attachments/assets/c7ebc00c-570d-426c-9567-e231b94f6051)

解决方案：
URL中把JPEG换成PNG
![Snipaste_2024-07-25_11-41-01](https://github.com/user-attachments/assets/9c8347ce-e3d2-4b5f-bf9f-9f60c7c53cc0)

**Comment by CrazyZhang666** [comment]
我测试改成PNG后无法打开头像链接

**Comment by SomunsMo** [comment]
> 我测试改成PNG后无法打开头像链接

我猜测可能和上传时的格式有关，可能你上传时时JPEG的图片，我上传的是PNG的图片

**Comment by SomunsMo** [comment]
刚才进行了头像上传测试，确实是和上传时的格式有关
更改前（Png格式）
![Test1](https://github.com/user-attachments/assets/281b11b2-6d30-4416-9ea8-8672c8ab7c6f)

更改后（JPEG格式）
![Test2](https://github.com/user-attachments/assets/a24cb2b0-2915-4f40-bbe6-35adf20e7a5e)

**Comment by CrazyZhang666** [comment]
这个后续会修复

**Comment by 761123300** [comment]
已修复
